export enum AnalyticsAction {
  CUSTOMIZE = 'customize',
  DEDICATE = 'dedicate',
  DOWNLOAD = 'download',
  CTA_WA_MODAL = 'cta_whatsapp_modal',
  CTA_WA_POST_DOWNLOAD = 'cta_whatsapp_post_download',
  CTA_WA_GALLERY = 'cta_whatsapp_gallery',
  SHARE_CONFIRM_OPEN = 'share_confirm_open',
  SHARE_CONFIRM_EXECUTED = 'share_confirm_executed',
  GALLERY_VIEW = 'gallery_view',
  GALLERY_EMPTY_VIEW = 'gallery_empty_view',
  GALLERY_SESSION_CLICK = 'gallery_session_click',
  GALLERY_OPENED = 'gallery_opened',
  SESSION_VIEW = 'session_view',
  SESSION_OPENED = 'session_opened',
  PHOTO_VIEW = 'photo_view',
  SESSION_STARTED = 'session_started',
  SESSION_COMPLETED = 'session_completed',
  ALL_PHOTOS_GALLERY_GRID_OPENED = 'all_photos_gallery_grid_opened'
}
